#ifndef BSP_CONFIG_H
#define BSP_CONFIG_H

#include "usart.h"
#include "spi.h"
#include "dac.h"
#include "main.h"
#include "usbd_cdc_if.h"

/*
 * bsp_config.h — the ONLY file that changes when switching from F401RE to G431CB.
 *
 * Migration checklist:
 *  1. Re-generate .ioc for STM32G431CB
 *  2. Update BSP_CLI_UART / BSP_SPI_BUS to match new HAL handle names
 *  3. Verify GPIO pin names match (main.h regenerated by CubeMX)
 *  4. For G431CB: consider moving ADS1220 to hspi2 to avoid SPI mode switching
 */

/* ── CLI terminal — USB CDC ───────────────────────────────────────────────────
 * G431RB: CLI over USB CDC (PA11/PA12). UART4 (PC10/PC11) is for ESP32 display.
 * cli.c uses these macros instead of HAL_UART_Transmit/Receive directly.
 */
#define BSP_CLI_Send(buf, len)   CDC_Transmit_FS((uint8_t*)(buf), (uint16_t)(len))
#define BSP_CLI_Receive(pbyte)   CDC_CLI_Receive(pbyte)

/* ── Display UART ────────────────────────────────────────────────────────────
 * UART4 (PC10/PC11) — bidirectional bridge to ESP32 display.
 * Receives CLI commands from display; forwards terminal commands to display.
 */
#define BSP_DISPLAY_Send(buf, len)   HAL_UART_Transmit(&huart4, (uint8_t*)(buf), (uint16_t)(len), 100)
#define BSP_DISPLAY_Receive(pbyte)   HAL_UART_Receive(&huart4, (pbyte), 1, 0)

/* ── Shared SPI bus ──────────────────────────────────────────────────────────
 * All peripherals share SPI1. ADS1220 uses Mode 1; others use Mode 0.
 * bsp_temp.c switches mode around each ADS1220 transaction.
 */
#define BSP_SPI_BUS     (&hspi1)

/* ── Internal DAC for TEC amplitude ─────────────────────────────────────────
 * DAC1_OUT1 (PA4) = Crystal TEC,  DAC1_OUT2 (PA5) = Laser TEC
 */
#define BSP_DAC         (&hdac1)
#define BSP_DAC_CH_CRYSTAL  DAC_CHANNEL_1
#define BSP_DAC_CH_LASER    DAC_CHANNEL_2

/* ── Chip-select GPIOs ───────────────────────────────────────────────────────
 * Pin names come from main.h (generated by CubeMX).
 */
#define BSP_ADC_CS_PORT     ADC_CS_GPIO_Port
#define BSP_ADC_CS_PIN      ADC_CS_Pin

#define BSP_DAC_CS_PORT     DAC_CS_GPIO_Port
#define BSP_DAC_CS_PIN      DAC_CS_Pin

#define BSP_DRV1_CS_PORT    DRV1_CS_GPIO_Port
#define BSP_DRV1_CS_PIN     DRV1_CS_Pin

#define BSP_DRV2_CS_PORT    DRV2_CS_GPIO_Port
#define BSP_DRV2_CS_PIN     DRV2_CS_Pin

/* ── DRV8873S direction control ──────────────────────────────────────────────
 * DRV1 = Crystal TEC,  DRV2 = Laser TEC
 */
#define BSP_DRV1_IN1_PORT    DRV1_IN1_GPIO_Port
#define BSP_DRV1_IN1_PIN     DRV1_IN1_Pin
#define BSP_DRV1_IN2_PORT    DRV1_IN2_GPIO_Port
#define BSP_DRV1_IN2_PIN     DRV1_IN2_Pin
#define BSP_DRV1_NSLEEP_PORT DRV1_nSLEEP_GPIO_Port
#define BSP_DRV1_NSLEEP_PIN  DRV1_nSLEEP_Pin

#define BSP_DRV2_IN1_PORT    DRV2_IN1_GPIO_Port
#define BSP_DRV2_IN1_PIN     DRV2_IN1_Pin
#define BSP_DRV2_IN2_PORT    DRV2_IN2_GPIO_Port
#define BSP_DRV2_IN2_PIN     DRV2_IN2_Pin
#define BSP_DRV2_NSLEEP_PORT DRV2_nSLEEP_GPIO_Port
#define BSP_DRV2_NSLEEP_PIN  DRV2_nSLEEP_Pin

/* ── NTC thermistor: Steinhart-Hart coefficients ─────────────────────────────
 * Replace with values from your NTC datasheet or calibration.
 * Example below is for a generic 100 kΩ NTC at 25°C (B=3950 K).
 * Calculate A/B/C from three calibration points using the S-H equation.
 */
#define BSP_NTC_SH_A    8.757e-4f
#define BSP_NTC_SH_B    2.535e-4f
#define BSP_NTC_SH_C    1.838e-7f

/* ── NTC voltage divider ─────────────────────────────────────────────────────
 * ADS1220 internal reference = 2.048 V
 * R_series = resistor in series with NTC (populate value from schematic)
 */
#define BSP_NTC_VREF_V       2.048f
#define BSP_NTC_RSERIES_OHM  10000.0f

/* ── Laser diode hardware current limit ──────────────────────────────────────
 * Absolute max the DAC8562S + driver circuit can deliver (hardware spec).
 * DAC code 0xFFFF maps to this value. The software limit in laser_control.c
 * can be set lower via CLI but never exceeds this value.
 */
#define BSP_LASER_MAX_CURRENT_A  2.0f

/* ── ADS1220 data rate ───────────────────────────────────────────────────────
 * 0x00 → 20 SPS: lowest noise, best for 5 mK stability requirement.
 * Increase to 0x20 (90 SPS) if faster response is needed during tuning.
 */
#define BSP_ADS1220_DR_20SPS   0x00u
#define BSP_ADS1220_DR_90SPS   0x20u
#define BSP_ADS1220_DATA_RATE  BSP_ADS1220_DR_20SPS

#endif /* BSP_CONFIG_H */
